version: 2.1

orbs:
  slack: circleci/slack@4.10.1

jobs:
  print-a-message:
    docker:
      - image: cimg/base:2022.03
    parameters:
      message:
        type: string
    steps:
      - run: echo << parameters.message >>
  my_deploy_job:
    docker:
      - image: cimg/base:2022.03
    steps:
      - run: echo "Deploy"


workflows:
  my-workflow:
    jobs:
      - print-a-message:
          message: Hello!
      - slack/on-hold:
          context: slack-secrets
          requires:
            - print-a-message
      - pause_workflow:
          requires:
            - print-a-message
            - slack/on-hold
          type: approval
      - my_deploy_job:
          requires:
            - pause_workflow

